name: smart_queue_management_system_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.11
  animated_text_kit: ^4.2.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1


  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
  - images/